name: nizvpn
description: Simple VPN using Platform Channel
publish_to: "none"
version: 1.1.2+12

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  collection: ^1.15.0
  device_apps: ^2.1.1
  device_info: ^2.0.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  firebase_crashlytics: ^2.2.3
  flutter_inapp_purchase: 
    git:
      url: https://github.com/mgonzalezc/flutter_inapp_purchase.git
      ref: fix/mindapps_fix
  in_app_purchase: 3.0.1
  app_tracking_transparency: ^2.0.2+1
  google_fonts: ^2.1.0
  in_app_review: 2.0.3
  in_app_update: ^3.0.0
  introduction_screen: ^3.0.0 
  line_icons: ^2.0.1
  lottie: ^1.2.1
  ndialog: ^4.1.0
  package_info: ^2.0.2
  provider: ^6.0.1
  pull_to_refresh:
    git:
      url: https://github.com/peng8350/flutter_pulltorefresh.git
      ref: nullsafety
  share: ^2.0.4
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  snapping_sheet: ^3.1.0
  firebase_core: ^1.7.0
  firebase_analytics: ^9.1.2
  firebase_messaging: ^11.2.8
  stack_appodeal_flutter: 3.0.0
  http: ^0.13.4
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/logo_android.png"
  image_path_ios: "assets/icons/logo_ios.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/icons/"
    - "assets/icons/flags/"
    - "assets/languages/"
    - "assets/animations/"
  fonts:
    - family: NerdVPNIcon
      fonts:
        - asset: assets/fonts/NerdVPNIcon.ttf
